#- module: nginxupstream
  #metricsets: ["status"]
  #enabled: true
  #period: 10s

  # Nginx hosts
  #hosts: ["http://127.0.0.1/"]

  # Path to server status. Default nginx_upstream_status?format=json
  #server_status_path: "nginx_upstream_status?format=json"
